# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Error10 Model.
  class Error10 < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash['code'] = 'code'
        @_hash['message'] = 'message'
      end
      @_hash
    end

    def initialize(code = nil,
                   message = nil)
      @code = code
      @message = message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash['code']
      message = hash['message']

      # Create object from extracted values.
      Error10.new(code,
                  message)
    end
  end
end
