# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # NewPet Model.
  class NewPet < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :tag

    # A mapping from model property names to API property names.
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash['name'] = 'name'
        @_hash['tag'] = 'tag'
      end
      @_hash
    end

    def initialize(name = nil,
                   tag = nil)
      @name = name
      @tag = tag
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      tag = hash['tag']

      # Create object from extracted values.
      NewPet.new(name,
                 tag)
    end
  end
end
