# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Pet Model.
  class Pet < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [Long]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :tag

    # A mapping from model property names to API property names.
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash['name'] = 'name'
        @_hash['id'] = 'id'
        @_hash['tag'] = 'tag'
      end
      @_hash
    end

    def initialize(name = nil,
                   id = nil,
                   tag = nil)
      @name = name
      @id = id
      @tag = tag
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash['name']
      id = hash['id']
      tag = hash['tag']

      # Create object from extracted values.
      Pet.new(name,
              id,
              tag)
    end
  end
end
