# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  #  swagger_petstore client class.
  class SwaggerPetstoreClient
    # Singleton access to client controller.
    # @return [APIController] Returns the controller instance.
    def client
      APIController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
