/*
 * BibcodeQueryLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package edu.harvard.adsabs;

import edu.harvard.adsabs.controllers.*;
import edu.harvard.adsabs.http.client.HttpClient;

public class BibcodeQueryClient {
    /**
     * Singleton access to BibcodeQueryBinding controller
     * @return	Returns the BibcodeQueryBindingController instance 
     */
    public BibcodeQueryBindingController getBibcodeQueryBinding() {
        return BibcodeQueryBindingController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public BibcodeQueryClient() {
    }

}